name: SHA Validation
on:
  workflow_dispatch:
jobs:
  check-sha:
    runs-on: ubuntu-latest
    outputs:
      skip_build: ${{ steps.check.outputs.skip_build }}
    steps:
      - name: Check Current SHA
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.sha;
            console.log(`Current SHA: ${sha}`);
            const runs =
              await github.rest.actions.listWorkflowRunsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                status: 'success'
              });
            const found = runs.data.workflow_runs.find(run =>
              run.head_sha === sha &&
              run.name === 'SHA Validation' &&
              run.id !== context.runId
            );
            if (found) {
              core.setOutput('skip_build','true');
              console.log('SHA already processed');
            } else {
              core.setOutput('skip_build','false');
              console.log('New SHA');
            }
  build:
    needs: check-sha
    if: needs.check-sha.outputs.skip_build == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Build
        run: |
          echo "Running Build"
          sleep 15
          echo "Build Complete"
  skipped:
    needs: check-sha
    if: needs.check-sha.outputs.skip_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Skip Message
        run: |
          echo "Build already completed for this SHA"
